### this ones are used for the certificate authority roles, jinja templates and some comparsions feel free and change to match your environment values.
var_group:
  node_01_ip_address: "10.20.10.10"
  node_02_ip_address: "10.20.10.11"
  node_03_ip_address: "10.20.10.12"
  keepalived_VIP_ip_address: "10.20.10.13"
  node_01_ip_address_dns: "ip-10-20-10-10"
  node_02_ip_address_dns: "ip-10-20-10-11"
  node_03_ip_address_dns: "ip-10-20-10-12"
  keepalived_VIP_ip_address_dns: "ip-10-20-10-13"
  node_01_short_name: "hckv01"
  node_02_short_name: "hckv02"
  node_03_short_name: "hckv03"
  node_01_fqdn: "hckv01.fpn.local"
  node_02_fqdn: "hckv02.fpn.local"
  node_03_fqdn: "hckv03.fpn.local"
  domain_fqdn: "lab.local"
  hashicorp_cluster_name: "hckvclu01"
  hashicorp_cluster_name_fqdn: "hckvclu01.lab.local"
  interface_name: "eth0"
  # percona_node_01_short_name: "percdbtest01"
  # percona_node_02_short_name: "percdbtest02"
  # percona_node_03_short_name: "percdbtest03"
