### this ones are used for the certificate authority roles, jinja templates and some comparsions feel free and change to match your environment values.
var_group:
  node_01_ip_address: "10.44.244.10"
  node_02_ip_address: "10.44.244.11"
  node_03_ip_address: "10.44.244.12"
  keepalived_VIP_ip_address: "10.44.244.13"
  node_01_ip_address_dns: "ip-10-44-244-10"
  node_02_ip_address_dns: "ip-10-44-244-11"
  node_03_ip_address_dns: "ip-10-44-244-12"
  keepalived_VIP_ip_address_dns: "ip-10-44-244-13"
  node_01_short_name: "eqfprdkv01"
  node_02_short_name: "eqfprdkv02"
  node_03_short_name: "eqfprdkv03"
  node_01_fqdn: "eqfprdkv01.fpn.local"
  node_02_fqdn: "eqfprdkv02.fpn.local"
  node_03_fqdn: "eqfprdkv03.fpn.local"
  domain_fqdn: "fpn.local"
  hashicorp_cluster_name: "eqfprdkvclu01"
  hashicorp_cluster_name_fqdn: "eqfprdkvclu01.fpn.local"
  interface_name: "ens192"
  percona_node_01_short_name: "eqfpercdbprd01"
  percona_node_02_short_name: "eqfpercdbprd02"
  percona_node_03_short_name: "eqfpercdbprd03"